#!/usr/bin/env python3
"""Fail closed when a production build input can float."""

from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
BASE_DIGEST = "sha256:1808b31ef43e9c521cde5884ba4df9ec26d8d503a314cea787590f8550358a63"
BASE_REFERENCE = f"continuumio/miniconda3:26.5.3-1@{BASE_DIGEST}"
CORE_SHA = "2bfaccc48dd49e71a5b6d9b3011808e127dd00cd"
LOCKS = {
    "linux-64": ROOT / "locks" / "conda-linux-64.lock",
    "linux-aarch64": ROOT / "locks" / "conda-linux-aarch64.lock",
}


def require(condition: bool, message: str) -> None:
    if not condition:
        raise SystemExit(f"supply-chain verification failed: {message}")


def verify_lock(platform: str, path: Path) -> None:
    lines = path.read_text(encoding="utf-8").splitlines()
    require(lines[0] == "# Generated by conda-lock.", f"{path.name} is not generated by conda-lock")
    require(f"# platform: {platform}" in lines[:5], f"{path.name} platform mismatch")
    require("@EXPLICIT" in lines, f"{path.name} is not an explicit lock")

    conda_artifacts = [line for line in lines if line.startswith("https://")]
    pip_artifacts = [line.removeprefix("# pip ") for line in lines if line.startswith("# pip ")]
    require(conda_artifacts, f"{path.name} has no Conda artifacts")
    require(pip_artifacts, f"{path.name} has no Python artifacts")
    require(
        all(re.search(r"#[0-9a-f]{32}$", line) for line in conda_artifacts),
        f"{path.name} contains a Conda artifact without an exact checksum",
    )

    core_requirement = (
        "hummingbot @ git+https://github.com/hummingbot/hummingbot.git@" + CORE_SHA
    )
    require(
        pip_artifacts.count(core_requirement) == 1,
        f"{path.name} must contain exactly the approved Hummingbot core commit",
    )
    for requirement in pip_artifacts:
        if requirement == core_requirement:
            continue
        require(
            re.search(r" @ https://.+#sha256=[0-9a-f]{64}$", requirement) is not None,
            f"unhashed Python artifact in {path.name}: {requirement}",
        )


def lock_set_digest() -> str:
    digest = hashlib.sha256()
    for path in LOCKS.values():
        file_digest = hashlib.sha256(path.read_bytes()).hexdigest()
        digest.update(f"{file_digest}  {path.as_posix().split('/locks/', 1)[1]}\n".encode())
    return digest.hexdigest()


def verify_sources() -> None:
    dockerfile = (ROOT / "Dockerfile").read_text(encoding="utf-8")
    compose = (ROOT / "docker-compose.yml").read_text(encoding="utf-8")
    environment = (ROOT / "environment.yml").read_text(encoding="utf-8")
    publish_workflow = (
        ROOT / ".github" / "workflows" / "docker_buildx_workflow.yml"
    ).read_text(encoding="utf-8")
    workflows = "\n".join(
        path.read_text(encoding="utf-8")
        for path in sorted((ROOT / ".github" / "workflows").glob("*.yml"))
    )

    require(BASE_REFERENCE in dockerfile, "Docker base is not pinned by tag and digest")
    require(dockerfile.count(f"FROM {BASE_REFERENCE}") == 2, "both stages must use the pinned base")
    require("apt-get" not in dockerfile, "Docker build still depends on APT")
    require("COPY environment.yml" not in dockerfile, "Docker build still consumes the floating solve input")
    require("conda env create" not in dockerfile, "Docker build still invokes a dependency solver")
    require("--no-build-isolation" in dockerfile, "Hummingbot build requirements could float")
    require(CORE_SHA in dockerfile, "Hummingbot core identity is absent from image metadata")
    require(CORE_SHA in environment, "Hummingbot core solve input changed")
    require(BASE_DIGEST in dockerfile, "base digest label is absent")
    require("io.condor.dependency-lock.sha256" in dockerfile, "lock digest label is absent")

    require(":latest" not in compose, "Compose still references a latest image")
    require("HUMMINGBOT_API_IMAGE:?" in compose, "Compose does not require an operator image identity")
    for image in ("emqx:5@sha256:", "postgres:16@sha256:"):
        require(image in compose, f"Compose image is not digest-pinned: {image.split('@')[0]}")
    require(":latest" not in workflows, "image publishing still emits a latest tag")
    require(
        "workflow_dispatch:" in publish_workflow and "pull_request:" not in publish_workflow,
        "registry publishing must require an explicit operator dispatch",
    )
    require(
        "hummingbot/hummingbot-api:sha-${{ env.SOURCE_SHA }}" in publish_workflow,
        "registry publishing does not use the exact source-SHA tag",
    )


def verify_image_labels(path: Path, source_sha: str, dependency_lock_sha: str) -> None:
    labels = json.loads(path.read_text(encoding="utf-8"))
    expected = {
        "org.opencontainers.image.revision": source_sha,
        "org.opencontainers.image.base.digest": BASE_DIGEST,
        "io.condor.hummingbot-core.revision": CORE_SHA,
        "io.condor.dependency-lock.sha256": dependency_lock_sha,
    }
    for key, value in expected.items():
        require(labels.get(key) == value, f"image label {key} is {labels.get(key)!r}, expected {value!r}")


def main() -> None:
    for platform, path in LOCKS.items():
        verify_lock(platform, path)
    verify_sources()

    if len(sys.argv) == 5 and sys.argv[1] == "--image-labels":
        verify_image_labels(Path(sys.argv[2]), sys.argv[3], sys.argv[4])
    elif len(sys.argv) != 1:
        raise SystemExit("usage: verify_supply_chain.py [--image-labels LABELS_JSON SOURCE_SHA LOCK_SHA]")

    print(f"LOCK_SET_SHA256={lock_set_digest()}")


if __name__ == "__main__":
    main()
